[ABOUT]
NAME = Live
AUTHOR = x4fab
VERSION = 1.1
DESCRIPTION = Loads real weather live.

; This parameter is static and moves weather controller into a different section
FOLLOWS_SELECTED_WEATHER = 0

; These parameters can be either static with 0 or 1, or dynamic with a query
FOLLOWS_SELECTED_TEMPERATURE = not SETTINGS/REAL_TEMPERATURE
FOLLOWS_SELECTED_WIND = not SETTINGS/REAL_WIND
